project: learn_dynamic_cool
group: test
expname: test

# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - ${model._target_}

hydra:
  run:
    dir: /home/conrard/GenDynDiff/gendyndiff/jobs/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    dir: ${oc.env:HYDRA_JOBS}/multirun/${now:%Y-%m-%d}/${expname}/
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    chdir: true
    env_set:
      WANDB_START_METHOD: thread
      # use subdir in running dir, so that git status can be logged
      # WANDB_DIR: ${oc.env:WANDB_DIR}

defaults:
  - _self_
  - data: dump
#    Decomment this parameter to get parallel job running
  # - override hydra/launcher: joblib
